* Windows
** I. Prerequisites

This section describes the prerequisites for installing and configuring kons-9
on Windows 10; in other words, it describes what should already be installed
and configured before you start. Please check over the list of prerequisites and
make sure they're all installed and properly configred before you try to install
and use kons-9.

*** MSYS2

*** Install MSYS2
Go to MSYS2 installation page, and follow sections I to III.
https://www.msys2.org/wiki/MSYS2-installation/

*** Try MSYS2
MSYS2 has several subsystems. After the installation of MSYS2 your Start menu
item MSYS2 64 will contain 5 subsystems. You can read more about them here:
https://www.msys2.org/wiki/MSYS2-introduction/

For our operations we will use MSYS2 MinGW x64. Pin it to some more convenient
location. Open your MSYS2 MinGW x64 and you will see a terminal window. From
now on I will call this window the Terminal.

At the terminal please enter ~pdw~ and press Enter. Your output will return
current directory that starts with ~/home/~ and will resemble the following.

#+begin_example
jacek@DESKTOP-M4FARGH MINGW64 ~
$ pwd
/home/jacek
#+end_example
