* Merging and changes

file:~/Programming/Lisp/kons-9/kons-9.asd::6

** Review of changes

I have not looked at the code for a while. Since then we had some notable
changes. Two new kaveh-devel-X branches have appeared and we have some demos to
investigate. I will concentrate on branch kaveh-devel-3 to review the changes.

My jacek-devel branch was merged with kaveh-devel-3 and I can see 100 files
changes since commit 0be7048. That includes a font and libraries dealing with
fonts.

** Continued
I will look at running the new code after the merger.
Let's see if [[file:~/Programming/Lisp/kons-9-notes/notes.org::*first run][first run]] link is any useful.

The instructions allowed me to compile and run the code, but I did not see the
sidebar with text. A quick look has revealed a (show-menu ) method, but at this
point I do not know how to proceed. The youtube video
https://youtu.be/THMzaVDaZP8 shows some 3D animations in action, but I do not
know how to run them.

Now I will read the instructions file:~/Programming/Lisp/kons-9/README.md::1

*** trying to run tests
Trying to run the test suite from the REPL has failed.
file:~/Programming/Lisp/kons-9/README.md::73
my code was identical merge of kaveh-devel-3
I will try main after some break

*** trying to run tests again
This time I will run the tests on main branch and will try tests in the REPL
file:~/Programming/Lisp/kons-9/README.md::77

I still got this error
#+begin_example
;    Error while parsing arguments to DEFMACRO CONFIDENCE::FLOAT-COMPARISON-THRESHOLD:
;      too many elements in
;        ('SINGLE-FLOAT MIN INACCURACY FLOAT1 FLOAT2)
#+end_example

file:~/Programming/Lisp/kons-9/testsuite/assertions.lisp::29

Removing ~'single-float~ in the assertions file I was able to execute
#+begin_src lisp
(ql:quickload "kons-9/testsuite")
#+end_src

I failed at my attempt to execute all available tests.

At this point I wonder to what extent the code is behind the README.md file?
