* Trying main demos
Following my lack of success described in:
file:~/Programming/Lisp/kons-9-notes/brainstorming/merging-and-changes.org::64

I had response from the author
https://github.com/kaveh808/kons-9/discussions/158#discussioncomment-3997035
which I am going to try.

** Latest main code
I am at my fork of main branch. I start slime. And see the Readme file.
file:~/Programming/Lisp/kons-9/README.md::41

*** I disagree with this code
file:~/Programming/Lisp/kons-9/README.md::47

#+begin_src lisp
(push (uiop:getcwd) ql:*local-project-directories*)
#+end_src

because on my system it sends me down the wrong path.
#+begin_example
(uiop:getcwd)
#P"/home/jacek/Programming/Lisp/kons-9-notes/brainstorming/"
#+end_example

I prefer my version
file:~/Programming/Lisp/kons-9-notes/notes.org::21
where I explicitly state the correct path for my system.

*** Running it
I have follwed the instructions and then ~(run)~ the code. The demo window is
visible and I have REPL

#+begin_example
KONS-9> (run)
#<SIMPLE-TASKS:CALL-TASK :FUNC #<FUNCTION (LAMBDA () :IN RUN) {53BE704B}> :STATUS :SCHEDULED {1004C79303}>

OpenGL Version: 4.6
KONS-9>
#+end_example

*** Trying demo
At this point with the ~(run)~ running in the REPL I have copied the code from
file:~/Programming/Lisp/kons-9/test/test-demos.lisp::11
to my REPL and ran it. It was a success. A bunch of 3D drawing flashed before my
eyes.

Is it possible that my last unsuccessful attempt was caused by running the demos before running ~(run)~?

On my system, after ~(run)~, I can use the REPL and load the following to see the demos.
#+begin_example
(load "~/Programming/Lisp/kons-9/test/test-demos.lisp")
#+end_example
